import { useCreateGeminiConversation } from "@workspace/api-client-react";
import { useLocation } from "wouter";
import { ChatInput } from "@/components/chat/ChatInput";
import { Sparkles } from "lucide-react";
import { motion } from "framer-motion";

export default function Home() {
  const [, setLocation] = useLocation();
  const createMutation = useCreateGeminiConversation();

  const handleCreateAndSend = async (message: string) => {
    const title = message.length > 40 ? `${message.substring(0, 40)}...` : message;
    
    try {
      const conv = await createMutation.mutateAsync({ data: { title } });
      // Redirect to the new chat with the initial message attached
      setLocation(`/chat/${conv.id}?q=${encodeURIComponent(message)}`);
    } catch (error) {
      console.error("Failed to create conversation:", error);
    }
  };

  return (
    <div className="flex-1 flex flex-col items-center justify-center relative w-full h-full px-4 overflow-hidden">
      {/* Background Image Generated by AI */}
      <div className="absolute inset-0 z-0">
        <img 
          src={`${import.meta.env.BASE_URL}images/empty-state-bg.png`}
          alt="Abstract decorative background"
          className="w-full h-full object-cover opacity-[0.15] mix-blend-screen pointer-events-none"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-background via-background/80 to-transparent" />
      </div>

      <div className="relative z-10 w-full max-w-4xl flex flex-col items-center justify-center gap-8 -mt-20">
        <motion.div 
          initial={{ opacity: 0, scale: 0.9, filter: 'blur(10px)' }}
          animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }}
          transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          className="flex flex-col items-center text-center gap-6"
        >
          <div className="w-16 h-16 rounded-3xl bg-gradient-to-br from-primary via-indigo-500 to-purple-600 flex items-center justify-center shadow-2xl shadow-primary/20 ring-1 ring-white/10 relative">
            <div className="absolute inset-0 bg-white/20 rounded-3xl opacity-0 hover:opacity-100 transition-opacity" />
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          
          <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-br from-white to-white/60">
            How can I help you today?
          </h1>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="w-full mt-4"
        >
          <ChatInput 
            onSend={handleCreateAndSend} 
            disabled={createMutation.isPending}
            autoFocus 
            className="shadow-2xl"
          />
        </motion.div>

        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6, duration: 1 }}
          className="flex flex-wrap items-center justify-center gap-3 mt-4"
        >
          {["Help me write an essay", "Analyze this code", "Plan a weekend trip", "Explain quantum physics"].map((suggestion) => (
            <button
              key={suggestion}
              onClick={() => handleCreateAndSend(suggestion)}
              disabled={createMutation.isPending}
              className="px-4 py-2 rounded-full bg-white/5 hover:bg-white/10 border border-white/5 text-sm text-foreground/80 hover:text-foreground transition-all duration-200"
            >
              {suggestion}
            </button>
          ))}
        </motion.div>
      </div>
    </div>
  );
}
